[[CopyArtifactPlugin-ChangeLog]]
== Change Log

:sectanchors:

[[CopyArtifactPlugin-Version1.43.1]]
=== 1.43.1

Release date: Mar 8, 2020

* Move the documentation to Github
(https://github.com/jenkinsci/copyartifact-plugin/pull/116[#116])

[[CopyArtifactPlugin-Version1.43]]
=== 1.43

Release date: Oct 5, 2019

* Support `+buildSelector+` in pipeline parameters
(https://github.com/jenkinsci/copyartifact-plugin/pull/114[#114])

[[CopyArtifactPlugin-Version1.42.1]]
=== 1.42.1

Release date: May 25, 2019

* Improved documents.
** Improve help texts of project names.
(https://github.com/jenkinsci/copyartifact-plugin/pull/107[#107])
** Fix spelling errors.
(https://github.com/jenkinsci/copyartifact-plugin/pull/112[#112])
* Removed scm-api plugin from dependencies.

[[CopyArtifactPlugin-Version1.42]]
=== 1.42

Release date: Mar 02, 2019

* Introduce a new selector: `+Last build with
artifacts+` (https://issues.jenkins-ci.org/browse/JENKINS-35417[JENKINS-35417])

[[CopyArtifactPlugin-Version1.41]]
=== 1.41

Release date: Jun 30, 2018

* `+copyArtifactPermission+` support:
** Declarative pipeline:
+
[source,groovy]
----
pipeline {
    agent any;
    options {
        copyArtifactPermission('job1,job2,...');
    }
    stages{...}
}
----
** Scripted pipeline
+
[source,groovy]
----
properties([
    copyArtifactPermission('job1,job2,...'),
]);
node {
    ...
}
----
* Retries downloading artifacts from ArtifactManagers supporting the
external URL feature like
https://plugins.jenkins.io/artifact-manager-s3/[Artifact
Manager S3 Plugin] .
** You MUST upgrade copyartifact from 1.40 if you
use https://plugins.jenkins.io/artifact-manager-s3/[Artifact
Manager S3 Plugin] (or plugins providing the external URL feature for
artifacts) and the upcoming version of Jenkins (might be 2.130).

[[CopyArtifactPlugin-Version1.40]]
=== 1.40

Release date: May 13, 2018

* *Targets Jenkins 2.118*
** There're no LTS yet, please consider to use copyartifact-1.40-beta-1
if you use LTS.
*** Be careful that 1.40-beta-1 doesn't support the exclude filter.
* ArtifactManager support
(https://issues.jenkins-ci.org/browse/JENKINS-22637[JENKINS-22637])
** You can copy artifacts that stores with `+ArtifactManager+`
implementations such as
https://plugins.jenkins.io/compress-artifacts/[Compress
Artifacts Plugin].

[[CopyArtifactPlugin-Version1.40-beta-1]]
=== 1.40-beta-1

Release date: Apr 29, 2018

* [line-through]*This is available via the experimental update center:
https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/#configuring-jenkins-to-use-experimental-update-center
** You can download it directly from
http://updates.jenkins-ci.org/download/plugins/copyartifact/1.40-beta-1/copyartifact.hpi
.
* ArtifactManager support
(https://issues.jenkins-ci.org/browse/JENKINS-22637[JENKINS-22637])
** You can copy artifacts that stores with `+ArtifactManager+`
implementations such as
https://plugins.jenkins.io/compress-artifacts/[Compress
Artifacts Plugin].
* *This version doesn't support exclude filters.*
** This will be fixed in the 1.40.
* The actual version of 1.40 will require Jenkins 2.118+.

[[CopyArtifactPlugin-Version1.39.1]]
=== 1.39.1

Release date: Apr 1, 2018

* Simple arguments for `+upstream+` selector
(`+TriggeredBuildSelector+`)

[[CopyArtifactPlugin-Version1.39]]
=== 1.39

Release date: Oct 29, 2017

* Now targets Jenkins >= 1.642.3 (was: 1.580)
* Provides pipeline syntax
(https://issues.jenkins-ci.org/browse/JENKINS-46700[JENKINS-46700])
** See link:#CopyArtifactPlugin-Pipelinesyntax[Pipeline syntax] for
details
* Provides descriptions in the update center
(https://issues.jenkins-ci.org/browse/JENKINS-44496[JENKINS-44496])
* Fix crash during the startup of Jenkins
(https://issues.jenkins-ci.org/browse/JENKINS-41773[JENKINS-41773])

[[CopyArtifactPlugin-Version1.38.1]]
=== 1.38.1

Release date: Jul 24, 2016

* Fixed: symlinks aren't created
(https://issues.jenkins-ci.org/browse/JENKINS-32832[JENKINS-32832])
** It occurred when symlinks are placed in subdirectories.
* Fixed: Empty variables aren't replaced to empty strings.
(https://issues.jenkins-ci.org/browse/JENKINS-36554[JENKINS-36554])

[[CopyArtifactPlugin-Version1.38]]
=== 1.38

Release date: Apr 17, 2016

* Fixed NPE when used with
https://www.cloudbees.com/products/cloudbees-jenkins-platform/enterprise-edition/features/templates-plugin[Templates
Plugin in Jenkins Enterprise Edition]
(https://issues.jenkins-ci.org/browse/JENKINS-32526[JENKINS-32526])
* Fixes wrong auto-completions and validations of "Permission to Copy
Artifact" with multi-configuration projects
(https://issues.jenkins-ci.org/browse/JENKINS-33257[JENKINS-33257])
* "Permission to Copy Artifact" is applicable to
https://plugins.jenkins.io/workflow-aggregator/[pipelines (aka.
workflows)].
* Displays errors and warnings when applying "Downstream build of" to
non-AbstractProject projects (like
https://plugins.jenkins.io/workflow-aggregator/[pipelines (aka.
workflows)]).
(https://issues.jenkins-ci.org/browse/JENKINS-33578[JENKINS-33578])

[[CopyArtifactPlugin-Version1.37]]
=== 1.37

Release date: Oct 4, 2015

* Added an option to 'Upstream build that triggered this job' to allow
upstream dependencies
(https://github.com/jenkinsci/copyartifact-plugin/pull/73[#73]).

[[CopyArtifactPlugin-Version1.36.1]]
=== 1.36.1

Release date: Nov 4, 2015

* Fixed problems with "Specified by a build parameter"
(https://issues.jenkins-ci.org/browse/JENKINS-30357[JENKINS-30357])
** Fixed NPE when specified undefined variables.
** Supports used in workflow jobs.
** Also supports immediate value specification for used in workflow jobs
($\{SELECTOR} in workflow jobs).
** Also supports variable expression ($\{SELECTOR} in non-workflow
jobs).

[[CopyArtifactPlugin-Version1.36]]
=== 1.36

Release date: Sep 6, 2015

* Introduced a field to specifi the suffix of the variable to store the
build number.
(https://issues.jenkins-ci.org/browse/JENKINS-18938[JENKINS-18938],
https://issues.jenkins-ci.org/browse/JENKINS-29812[JENKINS-29812])
** Added "Result variable suffix" in the "advanced" section.
** It allows you to store the build number to the variable named
"COPYARTIFACT_BUILD_NUMBER_(specified name)"
** Copyartifact behaves as before (creates the suffix from the source
project name) if you don't specified it. You don't need to reconfigure
existing configurations.

[[CopyArtifactPlugin-Version1.35.2]]
=== 1.35.2

Release date: Jul 4, 2015

* Fixed exception when configuring copyartifact with selectors provided
with other plugins (e.g.
https://plugins.jenkins.io/promoted-builds-simple/[Promoted
Builds Simple Plugin])
(https://issues.jenkins-ci.org/browse/JENKINS-28972[JENKINS-28972]).

[[CopyArtifactPlugin-Version1.35.1]]
=== 1.35.1

Release date: May 10, 2015

* Fixed the exception when saving the configuration in Jenkins 1.610
(https://issues.jenkins-ci.org/browse/JENKINS-28011[JENKINS-28011],
https://issues.jenkins-ci.org/browse/JENKINS-28094[JENKINS-28094]).
* Supports workflow's snippet generator
(https://issues.jenkins-ci.org/browse/JENKINS-28096[JENKINS-28096]).
* Avoids NPE caused by broken configurations
(https://issues.jenkins-ci.org/browse/JENKINS-27475[JENKINS-27475]).

[[CopyArtifactPlugin-Version1.35]]
=== 1.35

Release date: Mar 1, 2015

* Preserve symlinks when copying artifacts
(https://issues.jenkins-ci.org/browse/JENKINS-20546[JENKINS-20546],
https://issues.jenkins-ci.org/browse/JENKINS-22453[JENKINS-22453]).
* ParameterBuildFilter now works also for WorkflowRun
(https://issues.jenkins-ci.org/browse/JENKINS-26694[JENKINS-26694]).

[[CopyArtifactPlugin-Version1.34]]
=== 1.34

Release date: Jan 25, 2015

* *Now built for Jenkins-1.580 and later*
* Supports Workflow
(https://issues.jenkins-ci.org/browse/JENKINS-24887[JENKINS-24887])
** Please see
http://developer-blog.cloudbees.com/2015/01/copying-artifacts-between-builds-in.html[Copying
artifacts between builds in a Jenkins Workflow (CloudBees Development
Blog)] for details.

[[CopyArtifactPlugin-Version1.33]]
=== 1.33

Release date: Jan 17, 2015

* Added a new build selector "last completed build"
(https://issues.jenkins-ci.org/browse/JENKINS-16476[JENKINS-16476])

[[CopyArtifactPlugin-Version1.32.1]]
=== 1.32.1

Release date: Oct 20, 2014

* Fixed NPE when used in promotions (Promoted Builds plugin)
(https://issues.jenkins-ci.org/browse/JENKINS-25155[JENKINS-25155]).

[[CopyArtifactPlugin-Version1.32]]
=== 1.32

Release date: Oct 12, 2014

* Added a new build selector "Downstream build of"
(https://issues.jenkins-ci.org/browse/JENKINS-24626[JENKINS-24626])
* Fixed NPE on TriggeredBuildSelector when the upstream is removed.
(https://issues.jenkins-ci.org/browse/JENKINS-18804[JENKINS-18804])
* Fixed COPYARTIFACT_BUILD_NUMBER_XXX not declared in some cases
** Case 1: Used as a pre build step of maven project
(https://issues.jenkins-ci.org/browse/JENKINS-16028[JENKINS-16028])
** Case 2: Used in conditional-buildstep
(https://issues.jenkins-ci.org/browse/JENKINS-18762[JENKINS-18762])
* TriggeredBuildSelector is now applicable also for maven module builds
(https://issues.jenkins-ci.org/browse/JENKINS-14653[JENKINS-14653])

[[CopyArtifactPlugin-Version1.31]]
=== 1.31

Release date: Jul 21, 2014

* Supports absolute paths in CopyArtifactPermissionProperty.
(https://issues.jenkins-ci.org/browse/JENKINS-22038[JENKINS-22038])
* Fixed input validation problem when used with Cloudbees Template and
Cloudbees Folders plugin
(https://issues.jenkins-ci.org/browse/JENKINS-22828[JENKINS-22828])
* Fixed: Promotion permalinks not offered when job name is parameterized
(https://issues.jenkins-ci.org/browse/JENKINS-22590[JENKINS-22590])
* Fixed: Name of COPYARTIFACT_BUILD_NUMER_ variable is incorrectly
documented
(https://issues.jenkins-ci.org/browse/JENKINS-15764[JENKINS-15764])
* Fixed: Project source of a multi-config project inside a folder not
working
(https://issues.jenkins-ci.org/browse/JENKINS-20940[JENKINS-20940])
* Added a parameter to specify whether to copy from the newest upstream
or the oldest one when triggered by multiple upstreams.
(https://issues.jenkins-ci.org/browse/JENKINS-11655[JENKINS-11655])
* Fixed: Copying from workspace drops files matching Ant's default
excludes
(https://issues.jenkins-ci.org/browse/JENKINS-14900[JENKINS-14900])
** *Specify explicitly files matching Ant's default excludes with
"Artifacts not to copy" if you need to exclude them.
* Added exclude filter.
(https://issues.jenkins-ci.org/browse/JENKINS-18662[JENKINS-18662])
* Fixed inproper help texts of filter. Copyartifact doesn't fail even
specified files don't really exist.
(https://issues.jenkins-ci.org/browse/JENKINS-23444[JENKINS-23444])

[[CopyArtifactPlugin-Version1.30]]
=== 1.30

Release date: Feb 16, 2014

* Added license information (MIT).
* Fixed ClassNotFound when maven plugin not installed
(https://issues.jenkins-ci.org/browse/JENKINS-15977[JENKINS-15977])
* Allow to specify named builds in Specific Build Selector
(https://issues.jenkins-ci.org/browse/JENKINS-19693[JENKINS-19693])
* Job Property to define projects that can copy artifacts
(https://issues.jenkins-ci.org/browse/JENKINS-20398[JENKINS-20398])
* Fixed startup failure without maven-plugin
(https://issues.jenkins-ci.org/browse/JENKINS-21274[JENKINS-21274])

[[CopyArtifactPlugin-Version1.29]]
=== 1.29

Release date: Jan 29, 2014

* Support (mostly) absolute path for job name +
i.e. job name can be fully qualified but not start with "/" +
required for backward compatibility
(https://issues.jenkins-ci.org/browse/JENKINS-19833[JENKINS-19833])
* The authorization of builds are considered (when used with
QueueItemAuthenticator). QueueItemAuthenticator is available from
Jenkins 1.520.
(https://issues.jenkins-ci.org/browse/JENKINS-14999[JENKINS-14999])
* Make fingerprinting artifacts optional. By default the old behavior is
preserved.
(https://issues.jenkins-ci.org/browse/JENKINS-12134[JENKINS-12134] and
this serves as a workaround for
https://issues.jenkins-ci.org/browse/JENKINS-17606[JENKINS-17606]).

[[CopyArtifactPlugin-Version1.28]]
=== 1.28

Release date: Sep 23, 2013

* Supports ItemGroup (Cloudbees folders)
* Added diagnostics log messages when using `+SpecificBuildSelector+`
(related to
https://issues.jenkins-ci.org/browse/JENKINS-18220[JENKINS-18220])
* Migrates configuration when upgraded from version 1.25 or earlier.
(https://issues.jenkins-ci.org/browse/JENKINS-17680[JENKINS-17680])

[[CopyArtifactPlugin-Version1.27]]
=== 1.27

Release date: May 01, 2013

* NPE renaming job after 1.26 format change.
(https://issues.jenkins-ci.org/browse/JENKINS-17447[JENKINS-17447])
* Optional Copy Artifact build step fails if no specific build's build
number is given.
(https://issues.jenkins-ci.org/browse/JENKINS-14266[JENKINS-14266])

[[CopyArtifactPlugin-Version1.26]]
=== 1.26

Release date: Mar 25, 2013

* Split filtering by build parameters into a separate configuration
field, solving a security problem related to job configuration and
upstream builds. Existing job configuration using this plugin will be
rewritten if you run at least one build after the upgrade; if you
immediately open the configuration page you will need to manually
restore the upstream project field.
(https://issues.jenkins-ci.org/browse/JENKINS-13222[JENKINS-13222])
* Gets artifacts from jobs higher in the upstream chain. (pull request
#18)

[[CopyArtifactPlugin-Version1.25]]
=== 1.25

Release date: Nov 06, 2012

* Better diagnostics for copy failures.
(https://issues.jenkins-ci.org/browse/JENKINS-14262[JENKINS-14262],
https://issues.jenkins-ci.org/browse/JENKINS-15726[JENKINS-15726])

[[CopyArtifactPlugin-Version1.24]]
=== 1.24

Release date: Oct 03, 2012

* Continued fix for the case of a Windows slave with Unix master.
(https://issues.jenkins-ci.org/browse/JENKINS-13515[JENKINS-13515])

[[CopyArtifactPlugin-Version1.23]]
=== 1.23

Release date: Sep 21, 2012

* Failure on some Windows machines introduced in 1.22.
(https://issues.jenkins-ci.org/browse/JENKINS-13515[JENKINS-13515])

[[CopyArtifactPlugin-Version1.22]]
=== 1.22

Release date: Apr 16, 2012

* Hierarchical project support.

[[CopyArtifactPlugin-Version1.21]]
=== 1.21

Release date: Jan 12, 2012

* Revisited
https://issues.jenkins-ci.org/browse/JENKINS-12134[JENKINS-12134]
implementation to hide the computation overhead to the actual copy
operation.

[[CopyArtifactPlugin-Version1.20]]
=== 1.20

Release date: Dec 16, 2011

* Copying artifacts now also
https://wiki.jenkins.io/display/JENKINS/Fingerprint[fingerprints] them
automatically (on both source and destination)!
(https://issues.jenkins-ci.org/browse/JENKINS-12134[JENKINS-12134])

[[CopyArtifactPlugin-Version1.19]]
=== 1.19

Release date: Nov 28, 2011

* Using "Upstream build which triggered" with "Last successfull"
fallback uses last build as fallback and not last successful.
(https://issues.jenkins-ci.org/browse/JENKINS-11828[JENKINS-11828])
* Improve a misleading error message.
(https://issues.jenkins-ci.org/browse/JENKINS-10762[JENKINS-10762])
* Added hyperlinks to console output
* Added german translation

[[CopyArtifactPlugin-Version1.18]]
=== 1.18

Release date: Jul 24, 2011

* Copy only artifacts run for a particular matrix build (not those
inherited from previous builds) in Jenkins 1.413+.
(https://issues.jenkins-ci.org/browse/JENKINS-10214[JENKINS-10214])

[[CopyArtifactPlugin-Version1.17]]
=== 1.17

Release date: Jul 24, 2011

* Add support for multiconfiguration(matrix) projects with upstream
build selector.
(https://issues.jenkins-ci.org/browse/JENKINS-9729[JENKINS-9729])
* Add an option for upstream build selector to use last successful build
when job is not triggered by upstream job.
(https://issues.jenkins-ci.org/browse/JENKINS-10225[JENKINS-10225])
* Partial fix for
https://issues.jenkins-ci.org/browse/JENKINS-9741[JENKINS-9741] to
preserve permissions on the copied artifacts when using the "flatten"
option.

[[CopyArtifactPlugin-Version1.16]]
=== 1.16

Release date: Apr 17, 2011

* Add build selector to select the upstream build that triggered this
job. (https://issues.jenkins-ci.org/browse/JENKINS-8999[JENKINS-8999])
* Avoid NullPointerException triggered by
https://plugins.jenkins.io/build-pipeline-plugin/[Build
Pipeline Plugin].
(https://issues.jenkins-ci.org/browse/JENKINS-9359[JENKINS-9359])
* Allow filters in project name field to match all build variables, not
just parameters.
(https://issues.jenkins-ci.org/browse/JENKINS-9327[JENKINS-9327]) +
*Compatibility Note*: More variables are now matched, but values for
boolean parameters must now be specified as `+true+` and `+false+`
(previously yes/no, on/off and 1/0 were also accepted).
* Make text field for project name wider.
(https://issues.jenkins-ci.org/browse/JENKINS-9373[JENKINS-9373])
* Investigated permissions problem with using parameters to select a
particular matrix configuration or maven module; this is fixed in
Jenkins core 1.406.
(https://issues.jenkins-ci.org/browse/JENKINS-9293[JENKINS-9293])

[[CopyArtifactPlugin-Version1.15]]
=== 1.15

Release date: Apr 11, 2011

* Add note in "project not found" console message that error may be due
to permission settings as well as invalid name.
* Removed workaround code for
https://issues.jenkins-ci.org/browse/JENKINS-5977[JENKINS-5977] now that
minimum required Jenkins version for this plugin has that issue fixed.
* Updates for Jenkins

[[CopyArtifactPlugin-Version1.14]]
=== 1.14

Release date: Feb 24, 2011

* Rerelease 1.13 to properly set required Jenkins version.

[[CopyArtifactPlugin-Version1.13]]
=== 1.13

Release date: Feb 10, 2011

* Prevent access to artifacts of private jobs.
(https://issues.jenkins-ci.org/browse/JENKINS-8727[JENKINS-8727])
** For a fixed project name, check at save-config time and disallow use
of jobs the current user cannot see.
** For parameterized names, check at build time that the source job is
accessible to all authenticated users.
* Record build number of selected build into environment for later build
steps to reference. More detail in help text for build selector.
(https://issues.jenkins-ci.org/browse/JENKINS-8722[JENKINS-8722])
* Add support for filtering on build parameters, such as "latest stable
build with parameter FOO=bar". More detail in help text for project
name. (https://issues.jenkins-ci.org/browse/JENKINS-8657[JENKINS-8657])

[[CopyArtifactPlugin-Version1.12]]
=== 1.12

Release date: Jan 30, 2011

* Restore ability to copy artifacts from a maven project that were
archived with a post-build step (instead of maven automatic archiving).
(https://issues.jenkins-ci.org/browse/JENKINS-7752[JENKINS-7752])

[[CopyArtifactPlugin-Version1.11]]
=== 1.11

Release date: Nov 7, 2010

* Copy artifacts from _all_ modules/configurations when a maven/matrix
project is selected.
(https://issues.jenkins-ci.org/browse/JENKINS-7752[JENKINS-7752])
* Add extension point for how files are copied from source to target,
allowing other plugins to override default implementation using Jenkins'
FilePath class.
(https://issues.jenkins-ci.org/browse/JENKINS-7753[JENKINS-7753])
* Add note about limitation in copy-from-workspace feature.
(https://issues.jenkins-ci.org/browse/JENKINS-7751[JENKINS-7751])

[[CopyArtifactPlugin-Version1.10]]
=== 1.10

Release date: Oct 10, 2010

* Add option to copy from workspace of latest completed build.
(https://issues.jenkins-ci.org/browse/JENKINS-7130[JENKINS-7130]) +
Note: source and target jobs cannot both run on slave nodes; at least
one must be on the master node.
* Strip newlines in XML form of build selector parameters, to avoid
breaking ant execution on windows.
(https://issues.jenkins-ci.org/browse/JENKINS-7680[JENKINS-7680])

[[CopyArtifactPlugin-Version1.9]]
=== 1.9

Release date: Sep 28, 2010

* Now supports selecting a build based on its permalink, which allows
this plugin to work nicely with the promoted builds plugin.

[[CopyArtifactPlugin-Version1.8]]
=== 1.8

Release date: Jul 18, 2010

* Add parameter expansion in selecting a specific build number.
(https://issues.jenkins-ci.org/browse/JENKINS-6972[JENKINS-6972])

[[CopyArtifactPlugin-Version1.7]]
=== 1.7

Release date: May 12, 2010

* Add support for using a build parameter to specify the BuildSelector
used for copying artifacts.

[[CopyArtifactPlugin-Version1.6]]
=== 1.6

Release date: May 8, 2010

* Make build environment available to BuildSelectors.

[[CopyArtifactPlugin-Version1.5]]
=== 1.5

Release date: May 5, 2010

* Add Japanese localization.

[[CopyArtifactPlugin-Version1.3]]
=== 1.3

Release date: May 2, 2010

* Add option to flatten directories when copying, so all artifacts from
source project are copied directly into target directory.
(https://issues.jenkins-ci.org/browse/JENKINS-6345[JENKINS-6345])
* Add option to make the copy optional, so build doesn't fail if build,
workspace, or matching artifact is not found. This release changes the
default behavior when build is found but no artifacts were copied (now a
build failure, previously just reported "0 files copied").
* Add some help text about copying artifacts from Maven modules.
(https://issues.jenkins-ci.org/browse/JENKINS-6355[JENKINS-6355])

[[CopyArtifactPlugin-Version1.2]]
=== 1.2

Release date: Apr 17, 2010

* Add parameter expansion in name of project to copy from and add some
help text about copying from matrix jobs.
(https://issues.jenkins-ci.org/browse/JENKINS-6242[JENKINS-6242])
* Add extension point for how to select which build to copy artifacts
from. Includes selectors for latest successful/stable build or latest
saved ("keep forever") build. +
Other plugins known to implement this extension:
https://plugins.jenkins.io/promoted-builds-simple/[Promoted
Builds Simple Plugin]

[[CopyArtifactPlugin-Version1.1]]
=== 1.1

Release date: Mar 18, 2010

* Add workaround for hanging-slave issue to avoid problem until
https://issues.jenkins-ci.org/browse/JENKINS-5977[JENKINS-5977] is fixed
in core.
(https://issues.jenkins-ci.org/browse/JENKINS-5934[JENKINS-5934])

[[CopyArtifactPlugin-Version1.0]]
=== 1.0

Release date: Mar 7, 2010

* Initial release.
